### ISSUE TITLE
This is not web scale !!!

### ISSUE THREAD

**Issue by mudassir0909** [impressivewebs/HTML9-Responsive-Boilerstrap-js#114]
I also tried the **Universal** css selector

``` css
* {
    transform: scale(web);
}
```

Please help me out !!!
